import { Base } from "./Base.js";

/**
 * A base used for managers
 * @abstract
 */
class BaseManager extends Base {
    constructor(service) {
        super(service);
        /**
         * @note Ids are generated by /modules/id.js
         * @type {Collection<Snowflake, BaseBlock>}
         */
        this.cache = new Map();
    }
}

export { BaseManager };
